name: Release Python Package

on:
  push:
    tags:
       - 'v*'

jobs:
  build:
    name: Build and Test Code
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Get project version
      id: version
      run: echo "version=$(grep 'version' pyproject.toml | awk '{print $NF}' | sed 's/^"//; s/"$//')" >> $GITHUB_OUTPUT
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pip install pytest
        pytest
    - name: Build package
      run: python -m build --wheel
    - name: Store build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}_v${{ steps.version.outputs.version }}
        path: dist/

  release:
    name: Release python package to Github Releases
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_v${{ needs.build.outputs.version }}
          path: release-${{ github.ref_name }}/
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="Release ${{ github.ref_name }}" \
            --generate-notes \
            --verify-tag \
            ./release-${{ github.ref_name }}/*